#!/bin/sh

systemctl stop ModemManager.service

IF=`qmicli --device=/dev/cdc-wdm0 --device-open-proxy --get-wwan-iface`

#echo N > /sys/class/net/$IF/qmi/raw_ip
#qmicli -d /dev/cdc-wdm0 --wds-start-network=apn='internet'  --client-no-release-cid 

ifconfig $IF down
echo Y > /sys/class/net/$IF/qmi/raw_ip
ifconfig $IF up

qmicli -d /dev/cdc-wdm0 --dms-set-operating-mode=online
qmicli -d /dev/cdc-wdm0 --wds-set-autoconnect-settings=enabled
qmicli -d /dev/cdc-wdm0 --device-open-net="net-raw-ip|net-no-qos-header" --wds-start-network="apn='internet',ip-type=4" --client-no-release-cid  

qmicli -d /dev/cdc-wdm0  --wds-get-current-settings

udhcpc -f -s ./udhcpc_up.sh -i $IF

